### ISSUE TITLE
Please only focus on CSP

### ISSUE THREAD

**Issue by jvoisin** [i-net-software/dokuwiki-plugin-contentsecurity#2]
Currently, the extension is setting headers that the web server might send on its own.
It would be nice to only send CSP, that __can't__ be sent by the server, because of the nonce. Worst case, a configuration flag should do the job :)

Shall I send a pull-request to remove them?

**Comment by gamma** [comment]
Since the Plugin is WIP, you're welcome to contribute.

You're right about the header. Not sure if there are circumstances that an enduser can't set them from the server ... It might be ok to keep them around or make them optional.
